# Generated by Django 2.2 on 2019-04-06 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=20, verbose_name='小说的频道')),
            ],
            options={
                'verbose_name': '频道管理',
                'verbose_name_plural': '频道管理',
                'db_table': 'Channel',
            },
        ),
        migrations.CreateModel(
            name='Tage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '添加标签',
                'verbose_name_plural': '添加标签',
                'db_table': 'Tage',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='小说的类别')),
                ('tag_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.Channel', verbose_name='小说的频道')),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'TagModel',
            },
        ),
        migrations.CreateModel(
            name='NovelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='小说的名称')),
                ('novel_image', models.ImageField(blank=True, null=True, upload_to='novel/%Y/%m', verbose_name='小说的封面图')),
                ('novel_user', models.CharField(blank=True, default='佚名', max_length=30, null=True, verbose_name='小说的作者')),
                ('novel_byte', models.IntegerField(default=0, verbose_name='字节数')),
                ('novel_read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('novel_comment', models.IntegerField(default=0, verbose_name='评论量')),
                ('novel_text', models.TextField(blank=True, max_length=200, null=True, verbose_name='小说的简介')),
                ('novel_fave', models.IntegerField(default=0, verbose_name='小说的收藏数')),
                ('novel_next', models.IntegerField(default=0, verbose_name='浏览量')),
                ('novel_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='小说更新时间')),
                ('novel_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.TagModel', verbose_name='小说的类别')),
            ],
            options={
                'verbose_name': '小说管理',
                'verbose_name_plural': '小说管理',
                'db_table': 'NovelModel',
            },
        ),
        migrations.CreateModel(
            name='NovelCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='添加时间')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.NovelModel', verbose_name='关联电影')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.User', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '收藏小说',
                'verbose_name_plural': '收藏小说',
                'db_table': 'NovelCol',
            },
        ),
        migrations.CreateModel(
            name='NovelChaPter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelchapter_name', models.CharField(max_length=30, verbose_name='章节名称')),
                ('novelchapter_text', models.TextField(verbose_name='章节内容')),
                ('novelchapter_num', models.IntegerField(default=0, verbose_name='章节数')),
                ('novelchapter_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='章节更新时间')),
                ('novelchapter_cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': '章节管理',
                'verbose_name_plural': '章节管理',
                'db_table': 'NovelChaPter',
            },
        ),
    ]
