# Generated by Django 2.2 on 2019-04-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20190407_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelcol',
            name='user',
            field=models.IntegerField(default=1, verbose_name='关联用户的ID'),
            preserve_default=False,
        ),
    ]
