# Generated by Django 2.2 on 2019-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20190407_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='novel_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/novel/', verbose_name='小说的封面图'),
        ),
    ]
