# Generated by Django 2.2 on 2019-04-04 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='地址')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='URL别名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Auth')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='url地址')),
                ('info', models.TextField(verbose_name='简介')),
                ('logo', models.CharField(max_length=255, unique=True, verbose_name='封面')),
                ('star', models.PositiveSmallIntegerField(verbose_name='星级')),
                ('playnum', models.BigIntegerField(verbose_name='播放量')),
                ('commentnum', models.BigIntegerField(verbose_name='评论量')),
                ('area', models.CharField(max_length=255, verbose_name='上映地区')),
                ('release_time', models.DateField(verbose_name='上映时间')),
                ('length', models.CharField(max_length=100, verbose_name='播放时间')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('logo', models.CharField(max_length=255, unique=True, verbose_name='封面')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='昵称')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('info', models.TextField(verbose_name='个性简介')),
                ('face', models.CharField(max_length=255, unique=True, verbose_name='头像')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='注册时间')),
                ('uuid', models.UUIDField(unique=True, verbose_name='唯一标识符')),
            ],
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.User', verbose_name='会员外键')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('auths', models.ManyToManyField(blank=True, to='movie.Auth', verbose_name='拥有的权限')),
            ],
        ),
        migrations.CreateModel(
            name='Oplog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='登录IP')),
                ('reason', models.CharField(max_length=100, verbose_name='操作原因')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='登录时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Admin', verbose_name='所属管理员')),
            ],
        ),
        migrations.CreateModel(
            name='Moviecol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='添加时间')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie', verbose_name='关联电影')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.User', verbose_name='关联用户')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='movie.Tag', verbose_name='所属标签'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='添加时间')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie', verbose_name='所属电影')),
                ('user', models.ForeignKey(on_delete=True, to='movie.User', verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Adminlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='登录IP')),
                ('addtime', models.DateTimeField(auto_now=True, db_index=True, verbose_name='登录时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Admin', verbose_name='所属管理员')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.ManyToManyField(blank=True, to='movie.Role', verbose_name='角色'),
        ),
    ]
