# Generated by Django 2.2 on 2019-04-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='oplog',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Preview',
        ),
        migrations.RemoveField(
            model_name='role',
            name='auths',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '电影评论', 'verbose_name_plural': '电影评论'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影详情', 'verbose_name_plural': '电影详情'},
        ),
        migrations.AlterModelOptions(
            name='moviecol',
            options={'verbose_name': '电影收藏', 'verbose_name_plural': '电影收藏'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '电影标签', 'verbose_name_plural': '电影标签'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '会员', 'verbose_name_plural': '会员'},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'verbose_name': '会员登录日志', 'verbose_name_plural': '会员登录日志'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
        migrations.AlterModelTable(
            name='moviecol',
            table='Moviecol',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userlog',
            table='Userlog',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Adminlog',
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.DeleteModel(
            name='Oplog',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
