# Generated by Django 2.2 on 2019-04-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190407_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(max_length=255, unique=True, upload_to='', verbose_name='头像'),
        ),
    ]
