# Generated by Django 2.2 on 2019-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190407_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/movie/log/%Y/%m', verbose_name='电影封面'),
        ),
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='static/movie/face/%Y/%m', verbose_name='个人头像'),
        ),
    ]
